[project]
name = "baspacho"
description = "Direct solver for sparse SPD matrices for nonlinear optimization. Implements supernodal Cholesky decomposition algorithm, and supports GPU (CUDA)."
homepage = "https://github.com/facebookresearch/baspacho"
license = "MIT"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "1.0"

[tasks]
clean = "rm -rf ./build"
prepare = "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBASPACHO_USE_CUBLAS=0"
build = "cmake --build build -- -j16"
test = "ctest --test-dir build"

prepare_and_build = { depends-on = ["prepare", "build"] }
build_and_test = { depends-on = ["prepare_and_build", "test"] }
run_c = { depends-on = ["build_and_test"] }

[build-dependencies]
cmake = ">=3.28"
cxx-compiler = "1.9.0.*"
openblas = "*"

[dependencies]
openblas = "*"
